server:
  port: 8085
  context-path: /app
spring:
  application:
    name: boot-app1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: admin
    name: dataSource
management:
  security:
    enabled: false