server:
  port: 9080
spring:
  application:
    name: zull-proxy
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api
  routes:
    test:
      path: /redirect/**
      location: http://www.google.com
    byhost:
      path: /host/**
      location: http://localhost:9090
    byservice:
      path: /service/**
      location: boot-app1
    byclient:
      path: /client/**
      location: emp-client-service  