server:
  port: 9090
spring:
  application:
    name: emp-client-service
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      